export const languages = {
  vi: {
    title: "English Town trung tâm tiếng Anh cho người bận rộn",
    login: "Đăng nhập",
    login_with_google: "Đăng nhập với Google",
    or: "HOẶC",
    email: "Email",
    password: "Mật khẩu",
    login_title: "Đăng nhập để tiếp tục các khóa học",
    not_account: "Chưa có tài khoản ?",
    signup: "Đăng ký",
    email_empty: "Tài khoản không được để trống",
    password_empty: "Mật khẩu không được để trống",
    error_login: "Sai tài khoản hoặc mật khẩu!",
    course: "Khóa học",
    teacher: "Giáo viên",
    book_class: "Đặt lịch",
    cancel_book_class: "Hủy lịch",
    class_fulled: "Đã full lớp",
    class_closed: "Đã đóng",
    class_attended: "Tham dự",
    class_join_now: "Tham gia ngay",
    class_booked: "Lớp đã đặt",
    class_atteded_by: "Lớp đã tham gia",
    total_point_course: "Tổng điểm trung bình",
    class_available: "Lớp đang mở",
    class_upcoming: "Lớp đã đặt lịch",
    class_past: "Lớp đã học",
    empty_schedule_message: "Không có lớp học nào!",
    detail_class: "Chi tiết buổi học",
    confirm_book_schedule: "Xác nhận đặt lịch",
    close: "Đóng",
    confirm: "Xác nhận",
    book_schedule: "Đặt lịch",
    cancel_schedule: "Hủy lịch",
    confirm_cancel_schedule: "Xác nhận hủy lịch",
    confirm_book_schedule_sub_title:
      "Bạn có muốn đặt lịch cho lớp học bên dưới",
    confirm_cancel_schedule_sub_title:
      "Bạn có muốn hủy đặt lịch cho lớp học bên dưới",
    time_start: "Thời gian diễn ra",
    location: "Địa điểm",
    level: "Trình độ",
    room: "Phòng học",
    lesson: "Bài học",
    students: "Học viên",
    logout: "Đăng xuất",
    english: "Tiếng anh",
    vietnam: "Tiếng việt",
    flip_book: "Flip",
    quiz: "Quiz",
    slide: "Slide",
    header_event: "Sự kiện",
    header_online_course: "Giáo trình online",
    header_library: "Thư viện",
    header_schedule: "Lịch học",
    course_list: "Danh sách khóa học",
  },
  en: {
    title: "English Town English center for busy people",
    login_with_google: "Login with Google",
    or: "OR",
    login: "Login",
    email: "Email",
    password: "Password",
    login_title: "Sign in to continue the course",
    not_account: "No account ?",
    signup: "Singup",
    email_empty: "Account can not be empty",
    password_empty: "Password can not be blank",
    error_login: "Wrong account or password!",
    course: "Course",
    teacher: "Teacher",
    book_class: "Book",
    cancel_book_class: "Cancel",
    class_fulled: "Full class",
    class_closed: "Closed",
    class_attended: "Attended",
    class_join_now: "Join now",
    class_booked: "Booked",
    class_atteded_by: "Class attended",
    total_point_course: "Total point",
    class_available: "Available",
    class_upcoming: "Upcoming",
    class_past: "Pass",
    empty_schedule_message: "No classes available!",
    detail_class: "Lesson details",
    confirm_book_schedule: "Confirm booking schedule",
    close: "Close",
    confirm: "Confirm",
    book_schedule: "Book schedule",
    cancel_schedule: "Cancel schedule",
    confirm_cancel_schedule: "Confirm cancel schedule",
    confirm_book_schedule_sub_title:
      "Would you like to schedule the class below?",
    confirm_cancel_schedule_sub_title:
      "Would you like to cancel your booking for the class below?",
    time_start: "Start time",
    location: "Location",
    level: "Level",
    room: "Room",
    lesson: "Lesson",
    students: "Students",
    logout: "Logout",
    english: "English",
    vietnam: "Vietnamese",
    flip_book: "Flip book",
    quiz: "Quiz",
    slide: "Slide",
    header_event: "Event",
    header_online_course: "Online course",
    header_library: "Library",
    header_schedule: "Schedule",
    course_list: "Course List",
  },
};
